### ISSUE TITLE
Want to ask if you have a test project, or a API document

### ISSUE THREAD

**Issue by cppfuns** [lemuri/ews-qt#1]
I am using your open source project
https://github.com/lemuri/ews-qt
Want to ask if you have a test project, or a API document
Thank you for your dedication to the open source

**Comment by dantti** [comment]
Litteras mail is what uses it, tho both atm are on hold

**Comment by cppfuns** [comment]
Is this Litteras mail open source? If so, where can I download the code?

**Comment by dantti** [comment]
yes, it's GPL https://github.com/lemuri/litteras
